### ISSUE TITLE
 Coding Convention 정리

### ISSUE THREAD

**Issue by dotoleeoak** [dotoleeoak/skku-hun-2020#29]
각종 변수명, 패키지명 등 convention 통일 (PEP 준수)

**Comment by dotoleeoak** [comment]
@threedalpeng commit 전 black 이용할 것 권장 
설명: https://jonnung.dev/python/2019/11/10/python-black-uncompromising-code-formatter/

**Comment by threedalpeng** [comment]
Pycharm PEP-8 자동포맷팅 써도 괜찮겠지?

**Comment by dotoleeoak** [comment]
@threedalpeng black이 PEP-8 따르는거긴 한데 
PEP-8은 규칙 이름이고 툴은 가능하면 black 써
아마 autopep8이나 flake8로 되어있을 듯
